//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public int testId { get; set; }
        public int batchNo { get; set; }
        public System.DateTime testDate { get; set; }
        public string imgName { get; set; }
        public int label { get; set; }
        public Nullable<double> accuracy { get; set; }
        public int supId { get; set; }
        public string mcNo { get; set; }
    }
}
